---
- name: Check whether Helm is already there
  stat:
    path: /usr/local/bin/helm
  register: helm

- name: Retrieve helm binary archive
  unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: helm.stat.islnk is not defined
