---
- name: Ensure git is installed (RedHat).
  package:
    name: "{{ git_packages }}"
    state: present
    enablerepo: "{{ git_enablerepo | default(omit, true) }}"
  when:
    - not git_install_from_source
    - ansible_os_family == 'RedHat'

- name: Update apt packages
  become: true
  shell: apt update

- name: Ensure git is installed (Debian).
  apt:
    name: "{{ git_packages }}"
    state: present
  when:
    - not git_install_from_source
    - ansible_os_family == 'Debian'

- import_tasks: install-from-source.yml
  when: git_install_from_source
