apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hello-deployment
  labels:
    app: quarkus-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarkus-hello
  template:
    metadata:
      labels:
        app: quarkus-hello
    spec:
      containers:
        - name: quarkus-hello
          image: realvega/quarkus-hello
          ports:
            - containerPort: 8080