# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ANSIBLE_IP = "192.168.44.186"
TEST_M1_IP = "192.168.44.187"
TEST_N1_IP = "192.168.44.188"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "gsengun/ubuntu-bare-box-1804"
  config.vm.box_version = "1.0.0"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/vagrant", privileged: true

  # Define three VMs with static private IP addresses.
  boxes = [
    { :name => "m", :ip => TEST_M1_IP },
    { :name => "n1", :ip => TEST_N1_IP },
    { :name => "ansible", :ip => ANSIBLE_IP }
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |box|

      box.vm.hostname = opts[:name]
      box.vm.network :private_network, ip: opts[:ip]

      box.vm.provision "shell", inline: "cp /vagrant/id_rsa.pub /home/vagrant/.ssh/id_rsa.pub", privileged: false
      box.vm.provision "shell", inline: "cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"

      if ['m', 'n1'].include?(opts[:name])
        box.vm.provider :virtualbox do |v|
          v.memory = 2048
          v.cpus = 1
          v.linked_clone = true
        end
      end

      if opts[:name] == "ansible"
        box.vm.provider :virtualbox do |v|
          v.memory = 512
          v.cpus = 1
        end

        #SSH KEYS
        box.vm.provision "shell", inline: "cp /vagrant/id_rsa.pub /tmp/id_rsa.pub", privileged: false
        box.vm.provision "shell", inline: "chmod 600 /tmp/id_rsa.pub", privileged: false

        box.vm.provision "shell", inline: "cp /vagrant/id_rsa /tmp/id_rsa", privileged: false
        box.vm.provision "shell", inline: "chmod 600 /tmp/id_rsa", privileged: false

        # Ansible config
        box.vm.provision "shell", inline: "mkdir -p /etc/ansible", privileged: true
        box.vm.provision "shell", inline: "cp /vagrant/provision-aws/inventories/vagrant/ansible.cfg /etc/ansible/ansible.cfg", privileged: true, run: "always"
        box.vm.provision "shell", inline: "echo 'cd /vagrant/provision-aws' >> /home/vagrant/.bashrc"

        box.vm.provision "vagrant", type:"shell", run: "never", inline: "cd /vagrant/provision-aws && bash provision.sh vagrant", privileged: false
        #CODE: PKTCLSTRS
        box.vm.provision "aws", type:"shell", run: "never", inline: "cd /vagrant/provision-aws && bash provision.sh aws", privileged: false

        box.vm.provision "ansible_local" do |ansible|
          ansible.limit = "all"
          ansible.install_mode = "pip"
          ansible.version = "2.7.8"
          ansible.playbook = "/vagrant/provision-aws/playbooks/ping-playbook.yml"
          ansible.inventory_path = "/vagrant/provision-aws/inventories/vagrant/inventory"
        end
      end
    end
  end
end