---
- name: install python 2
  raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: install pip
  raw: test -e /usr/bin/pip || (apt-get -y update && apt-get install -y python-pip)

- name: run setup manually for gathering the facts
  setup: # aka gather_facts
